### ISSUE TITLE
Problem in running demo.ipynb

### ISSUE THREAD

**Issue by wangxinyu0922** [peteanderson80/bottom-up-attention#1]
>>> net = caffe.Net(prototxt, caffe.TEST, weights=weights)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Boost.Python.ArgumentError: Python argument types in
    Net.__init__(Net, str, int)
did not match C++ signature:
    __init__(boost::python::api::object, std::string, std::string, int)
    __init__(boost::python::api::object, std::string, int)

**Comment by peteanderson80** [comment]
Do any of [these suggestions](https://github.com/BVLC/caffe/issues/3220) help? I haven't experienced this problem. What OS / python version do you use?

**Comment by wangxinyu0922** [comment]
Well, I solved it by changing it to 
net = caffe.Net(prototxt, ,weights,caffe.TEST)
