### ISSUE TITLE
Tensorflow version ?

### ISSUE THREAD

**Issue by saranshvora** [peteanderson80/bottom-up-attention#13]
Hi,

I have a question. I would like to know whether you will be releasing a tensorflow version of your code ?

**Comment by peteanderson80** [comment]
Hi, I don't intend to port this to tensorflow. However, if you can find a tensorflow version of Faster R-CNN, then you could reuse all the python code here for processing and filtering the visual genome dataset. So an interested person could certainly do it! :)

**Comment by saranshvora** [comment]
Aah okay thank you for your answer :) I really appreciate it.
