### ISSUE TITLE
GloVe word embedding for top down attention model

### ISSUE THREAD

**Issue by ninoq206** [peteanderson80/bottom-up-attention#14]
Thank you for the fascinating paper and code! 

I notice that for the image captioning model, you decided to use the standard vocabulary and train the word embedding matrix from scratch. So I've been wondering if I apply the approach mentioned in your previous paper about Constrained Beam Search (pretrained GloVe vectors with expanded vocabulary), will it improve the performance of the model?

**Comment by peteanderson80** [comment]
Hi @ninoq206, in the constrained beam search paper, using pretrained (and fixed) GloVe vectors had only marginal impact on performance - the main goal was to be able to expand the model vocab at run time. We haven't investigated that here, but when I do eventually get time to release the captioning model I will include the constrained beam search code. 
cheers.

**Comment by ninoq206** [comment]
Thanks a lot for the thoughtful response. I'm trying to implement an image captioning model in Tensorflow using your top-down structure, and having your official implementation as reference would help immensely. Looking forward to it!
