### ISSUE TITLE
Struggling for installation

### ISSUE THREAD

**Issue by ozancaglayan** [peteanderson80/bottom-up-attention#15]
Hello,

I am heavily failing to build the shipped Caffe with anaconda, mainly linking errors w.r.t google protobuf. Been struggling for like 7-8 hours and I am pretty close to give up.

So the question is what are the modifications shipped in the `caffe/` folder? Can't we really use upstream Caffe?

**Comment by ozancaglayan** [comment]
OK finally fixed the problem. It's a mismatch between GCC >= 5 and current Anaconda's protobuf. For those who have this problem, apply the following patch to `caffe/CMakeLists.txt`:

```patch
--- a/caffe/CMakeLists.txt
+++ b/caffe/CMakeLists.txt
@@ -45,7 +45,7 @@ include(cmake/Dependencies.cmake)

 # ---[ Flags
 if(UNIX OR APPLE)
-  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -Wall")
+  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11 -fPIC -Wall")
 endif()

 caffe_set_caffe_link()
```

**Comment by peteanderson80** [comment]
Thanks for posting @ozancaglayan, this will be helpful info for others.
