### ISSUE TITLE
How to visualize the attention

### ISSUE THREAD

**Issue by haibin894609937** [peteanderson80/bottom-up-attention#16]
How to visualize the attention

**Comment by haibin894609937** [comment]
VQA attention output

**Comment by peteanderson80** [comment]
This repo only includes the bottom-up attention (Faster R-CNN) model from section 3.1 of the [paper](https://arxiv.org/pdf/1707.07998.pdf). The VQA model was built by [Damien Teney](https://www.damienteney.info/) from University of Adelaide in Matlab. Last I heard he doesn't plan to release the model. However, I will be releasing the captioning model (with attention visualization) in the next few weeks.

**Comment by peteanderson80** [comment]
We have now released the code for the captioning model: https://github.com/peteanderson80/Up-Down-Captioner. This includes a demo that shows the attention visualization for captioning.
thanks

**Comment by peteanderson80** [comment]
Sorry... wasn't exactly in a few weeks...

**Comment by haibin894609937** [comment]
thanks for your reply



来自 魅族 PRO 5



-------- 原始邮件 --------
发件人：Peter Anderson <notifications@github.com>
时间：周一 2月12日 13:01
收件人：peteanderson80/bottom-up-attention <bottom-up-attention@noreply.github.com>
抄送：haibin894609937 <liuhaibin210317@hotmail.com>,Author <author@noreply.github.com>
主题：Re: [peteanderson80/bottom-up-attention] How to visualize the attention (#16)


We have now released the code for the captioning model: https://github.com/peteanderson80/Up-Down-Captioner. This includes a demo that shows the attention visualization for captioning.
thanks
