### ISSUE TITLE
Hardware Requirement, does eval need that 12G GPU memory?

### ISSUE THREAD

**Issue by StephenZengCn** [peteanderson80/bottom-up-attention#3]
```
F0906 11:11:48.665238   945 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
```
i got this error when running demo.ipynb with a new picture size 416x449, but example pictures running success.

**Comment by StephenZengCn** [comment]
i have gpu 1080(8G memory)x4, is there anyway i can use multi gpu when predict?

**Comment by StephenZengCn** [comment]
cpu mode running success too

**Comment by StephenZengCn** [comment]
for generate feature, we need 12G per GPU?

**Comment by StephenZengCn** [comment]
any idea to generate feature with 8G GPU x4 on private image data, cpu is a long long time......

**Comment by peteanderson80** [comment]
From a computational perspective, the size of the input image doesn't matter as they are all resized to 600 pixels on the shortest side. 

The easiest way to reduce the memory requirement is to reduce the `SCALES` and `MAX_SIZE` image parameters at test time. The parameters are defined [here](https://github.com/peteanderson80/bottom-up-attention/blob/a8f4c8a0f15937553b41ee5d68827936bc473e4f/lib/fast_rcnn/config.py#L146-L151) but you can set the values in this [config file](https://github.com/peteanderson80/bottom-up-attention/blob/a8f4c8a0f15937553b41ee5d68827936bc473e4f/experiments/cfgs/faster_rcnn_end2end_resnet.yml#L15-L19).

This might reduce the quality / number of features a bit, so a better option would be to maybe chop the network in half after the RPN layers, then run it in two stages (saving intermediate outputs). This would require modifying the code and network though.

Hope that helps.

**Comment by StephenZengCn** [comment]
thx!

**Comment by yangshao** [comment]
@StephenZengCn  how to solve this problem finally?  I come across the same problem, and my gpu has 12g memory. Thanks.

**Comment by StephenZengCn** [comment]
12g is enough.
as anderson said, i extract feature by run it in two stage.
split models/vg/ResNet-101/faster_rcnn_end2end_final/train.prototxt to
models/vg/ResNet-101/faster_rcnn_end2end_final/rpn.prototxt
models/vg/ResNet-101/faster_rcnn_end2end_final/rcnn.prototxt
and modify some code in tools/generate_tsv.py
good luck

**Comment by yangshao** [comment]
@StephenZengCn Thanks for your reply. I'm new to caffe. So it is possible for your to share the modifications to run the demo.ipynb? Thanks  a lot!

**Comment by StephenZengCn** [comment]
i didn't use demo.ipynb, just use generate_tsv.py to extract bottom-up features.

**Comment by linuxjain** [comment]
@yangshao did u run demo.ipnb successfully ?

**Comment by coldmanck** [comment]
Hi @StephenZengCn 

Could you please share the scripts of them :)? I would really appreciate for the help.

**Comment by ZhuFengdaaa** [comment]
Does anyone have some no grad tricks like `Variable(data, volatile=True)` in Pytorch, which doing forward calculation only rather than saving blobs for each layer.

**Comment by raghavgoyal14** [comment]
@coldmanck : I faced the same issue and the model really needed close to 10.5 gb of memory on a GPU. So I made sure that I have one with enough memory.

**Comment by beckyli** [comment]
I also met this problem when using 11g GPU. How I can solve it?

**Comment by maoyj2333** [comment]
I use this code to extract feature from VG datasets, and I found it was caused by some images with big difference in aspect ratio, for example 281 * 500, faster rcnn will scale based on the shorter one, so making the larger one to large.

![image](https://user-images.githubusercontent.com/73008189/122693986-8c7a6880-d26e-11eb-8fa7-6bb3e7417dc2.png)

this code may work on 11G gpu
