### ISSUE TITLE
How l2-normalization over feature is implemented ? 

### ISSUE THREAD

**Issue by ZhuFengdaaa** [peteanderson80/bottom-up-attention#30]
[this paper](https://arxiv.org/pdf/1708.02711.pdf) states that L2 normalization of the image features is crucial for good performance. However, you just use pool5 data, which is average pooled to become a 2048 vector in [generate_tsv.py](https://github.com/peteanderson80/bottom-up-attention/blob/master/tools/generate_tsv.py)

I'm wondering if you have implemented L2-normalization over feature or not. If you did, please inform me how you do it. Thanks a lot~

**Comment by cengzy14** [comment]
I guess the L2 normalization is done in the data loading part of the VQA model part, like https://github.com/yuzcccc/vqa-mfb/blob/master/mfh_coatt_glove/vqa_data_layer.py

**Comment by ZhuFengdaaa** [comment]
Thanks, it does.
