### ISSUE TITLE
It seems I cannot download the trainval features from onedrive?

### ISSUE THREAD

**Issue by greathope** [peteanderson80/bottom-up-attention#31]
Can anyone give me another links?

**Comment by peteanderson80** [comment]
We are looking into it. We had another hosting solution but it was very expensive.

**Comment by peteanderson80** [comment]
I will reactive the old download links while we sort something out. 

 10 to 100 features per image (adaptive):
 - [2014 Train/Val Image Features (120K / 23GB)](https://storage.googleapis.com/bottom-up-attention/trainval.zip)
 - [2014 Testing Image Features (40K / 7.3GB)](https://storage.googleapis.com/bottom-up-attention/test2014.zip)
 - [2015 Testing Image Features (80K / 15GB)](https://storage.googleapis.com/bottom-up-attention/test2015.zip)
  
  36 features per image (fixed):
 - [2014 Train/Val Image Features (120K / 25GB)](https://storage.googleapis.com/bottom-up-attention/trainval_36.zip)
 - [2014 Testing Image Features (40K / 9GB)](https://storage.googleapis.com/bottom-up-attention/test2014_36.zip)
 - [2015 Testing Image Features (80K / 17GB)](https://storage.googleapis.com/bottom-up-attention/test2015_36.zip)

**Comment by greathope** [comment]
many thanks!

**Comment by peteanderson80** [comment]
The links in [README.md](https://github.com/peteanderson80/bottom-up-attention/blob/master/README.md) have been updated. Please use the new links.
