### ISSUE TITLE
The downloads links are too slow?

### ISSUE THREAD

**Issue by manoja328** [peteanderson80/bottom-up-attention#32]
Am I the only one experiencing slow download of the zipped features? Previous links used to be fast.

**Comment by peteanderson80** [comment]
The previous links were on Google cloud storage, but the downloads were very expensive.

If there is demand I can re-enable the old links on a [requester pays](https://cloud.google.com/storage/docs/requester-pays) basis. You would need to use your Google account and I think it would cost about $10 to do the fast download.

**Comment by ivy94419** [comment]
@manoja328 Have you download them successfully? Can you share with me. Thank you very much.

**Comment by ManasiPat** [comment]
I am not been able to download as well because of the speed. Can I get the downloads. I am ready to pay for the same. Thanks. I just need this file. https://imagecaption.blob.core.windows.net/imagecaption/trainval_36.zip.

**Comment by chejiao** [comment]
@ManasiPat  l also need this file.
can you share with me?
I'm willing to pay part of the cost.
You can contact me by email:2221090570@qq.com
Looking forward to your reply

**Comment by peteanderson80** [comment]
See the readme for new fast requester pays download links from google cloud storage. Should solve the problem.
