### ISSUE TITLE
Can sombody share the Pretrained features?

### ISSUE THREAD

**Issue by ivy94419** [peteanderson80/bottom-up-attention#37]
I used Chrome to download the features, but the speed is lower than 50kb/s and when downloading 50~100MB, it would interupt and when I redownload it will start from the begining.....
I feel helpless...

**Comment by TyrionChou** [comment]
me too！

**Comment by peteanderson80** [comment]
There is now an alternative download using google cloud storage that is very fast, but it is user pays - you need a google cloud storage account.
