### ISSUE TITLE
activation of the relation prediction

### ISSUE THREAD

**Issue by yuzcccc** [peteanderson80/bottom-up-attention#6]
@peteanderson80 
I saw the option "HAS_RELATION" in the cfg file. I turned it on and add a top[6] data for the proposal_target_layer and set the param `num_rel_classes` to 21(I am not sure if this is correct for the vg_1600-400-20 dataset) and start training, I got the following error:
```
File "/home/work/bottom-up-attention/tools/../lib/roi_data_layer/minibatch.py", line 55, in get_minibatch
    "Generation of gt_relations doesn't accomodate dropping objects"
AssertionError: Generation of gt_relations doesn't accomodate dropping objects
```
Is there something wrong with my setting?

**Comment by peteanderson80** [comment]
We investigated trying to predict relations between visual genome objects, so that we could also use relation predictions in our captioning / vqa models. Initial results didn't lead to improvement so we left out this part of the code. The HAS_RELATION setting was for this experiment and should be ignored.

**Comment by yuzcccc** [comment]
Curious that what kind of network architecture you had used to predict the relation. Is it convenient for you to briefly introduce it? Thanks a lot

**Comment by peteanderson80** [comment]
We basically added some extra layers taking pairs of object proposals. We used a loss function based on [TransE](http://papers.nips.cc/paper/5071-translating-embeddings-for-modeling-multi-relational-data.pdf), but we didn't really have time to fully investigate this.
