### ISSUE TITLE
binascii.Error: Incorrect padding

### ISSUE THREAD

**Issue by cswhjiang** [peteanderson80/bottom-up-attention#7]
Got ```binascii.Error: Incorrect padding``` when reading image 300104 from ```test2014/test2014_resnet101_faster_rcnn_genome.tsv.1``` with ```tools/read_tsv.py```. Anything wrong?

```
Traceback (most recent call last):
  File "read_tsv.py", line 64, in <module>
    read_and_save(os.path.join(in_dir, in_file), out_dir)
  File "read_tsv.py", line 45, in read_and_save
    item['features'] = np.frombuffer(base64.decodestring(item['features']), dtype=np.float32).reshape((item['num_boxes'], -1))
  File "/usr/lib64/python2.7/base64.py", line 321, in decodestring
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

**Comment by cswhjiang** [comment]
Solved. Features for image 300104, 147295, 321486 are duplicated. Just ignoring the binascii.Error will work.

**Comment by jamiechoi1995** [comment]
what does ''duplicated'' mean? I view the three images, they are totally different, and why their features will be duplicated?
![COCO_test2014_000000321486](https://user-images.githubusercontent.com/13494034/62032508-6a137800-b21c-11e9-8ddc-5133fa0939c5.jpg)
![Uploading COCO_test2014_000000147295.jpg…]()
![Uploading COCO_test2014_000000300104.jpg…]()

**Comment by kangkang59812** [comment]
> Solved. Features for image 300104, 147295, 321486 are duplicated. Just ignoring the binascii.Error will work.

Did you mean the three pictures are duplicated in test datasets? (total:40775, 3 of them are duplicated with others?)

**Comment by wtliao** [comment]
@jamiechoi1995 have you solved this issue? thanks

**Comment by gorou-gnm** [comment]
changing `tools/read_tsv.py`
from
```                item[field] = np.frombuffer(base64.decodestring(item[field]), 
                      dtype=np.float32).reshape((item['num_boxes'],-1))
to
```                item[field] = np.frombuffer(base64.decodestring(bytes(code, 
                       encoding="utf8")[2:-1])).reshape(item['num_boxes'],-1)
worked for me (python3)
