### ISSUE TITLE
Could you please list the platform version?

### ISSUE THREAD

**Issue by JohnnieXDU** [peteanderson80/bottom-up-attention#8]
When I make pycaffe follow your configuration, it always arise some annoying conflicts. Could you please list the platform used in your code? 

Besides, my environment is :
- Ubuntu16.04
- CUDA 8
- CUDNN 5.0
- Opencv2.4.13
- mkl2016
- NCCL

Is that worked?
Thanks~

**Comment by peteanderson80** [comment]
We used:
- Ubuntu 14.04
- python 2.7.6 (not anaconda)
- CUDA 8.0
- CUDNN 5.0
- OpenCV 3.2
- mkl 11.3.1
- NCCL

**Comment by JohnnieXDU** [comment]
Thanks!
