### ISSUE TITLE
are the features in order and alligned with the ROI pooling layer?

### ISSUE THREAD

**Issue by fawazsammani** [peteanderson80/bottom-up-attention#81]
Hello @peteanderson80 
Thanks for your work.
I'd like to ask. Are the 36 features aligned to the last layer of the Faster-RCNN where you use ROI pooling if I reshape them? i.e. if I reshape the features from (36,2048) to (6,6,2048), do I get the output of ROI pooling? Or have you shuffled them?

Thanks!

**Comment by peteanderson80** [comment]
No, that will not give the output of ROI pooling. The 36 features have bounding boxes that are the 36 most confident object proposals in the image, so they are in no particular order and can have different sizes, aspect ratios etc. depending on the image.
