### ISSUE TITLE
Can not download the pretrained model again.

### ISSUE THREAD

**Issue by tianyu0523** [peteanderson80/bottom-up-attention#84]
I can not open the dropbox link. Could you please update it?

**Comment by peteanderson80** [comment]
I justed tested both model links under the [Demo](https://github.com/peteanderson80/bottom-up-attention#demo) section and they worked fine. Can you check it again and post more details if you still have a problem?

**Comment by YangXiaocui1215** [comment]
I  also can not open the dropbox link. Could you please update it?
