### ISSUE TITLE
How about the image caption model?

### ISSUE THREAD

**Issue by JohnnieXDU** [peteanderson80/bottom-up-attention#9]
Hello, the attribute extraction net using bottom-up attention you proposed is impressing! It indeed boosts the image caption performance in the paper. Besides the attention model, I am also interested in the caption model designed in the paper. In the paper, you mentioned that your caption model achieves performance comparable to start-of-art on most evaluation metrics. So to compare with my own model, can you provide your captioning model implementation code?   :)

**Comment by peteanderson80** [comment]
Hi, we are happy to release the captioning model as well. So far it hasn't been the highest priority compared to other things but I will try to get it done.

**Comment by peteanderson80** [comment]
We have now released the code for the captioning model: https://github.com/peteanderson80/Up-Down-Captioner
thanks
