### ISSUE TITLE
downloading features is really slow

### ISSUE THREAD

**Issue by nilinykh** [peteanderson80/bottom-up-attention#91]
Hello,

the links to download features are very slow, and often they break right in the middle of the download. Is it possible to speed it up somehow / get an alternative link?
 
Thanks.

**Comment by peteanderson80** [comment]
Did you try the alternative Google Cloud Storage links? It's fast but it needs your own project id to pay the download cost.

**Comment by nilinykh** [comment]
Ah, right. Sorry, I should have been more attentive to the instructions in the repo.
Thanks!
