### ISSUE TITLE
Could not download the pretrained features properly

### ISSUE THREAD

**Issue by junchen14** [peteanderson80/bottom-up-attention#93]
when I download the features by wget https://imagecaption.blob.core.windows.net/imagecaption/trainval_36.zip

it always stop in the middle of downloading data. and it shows such error
2020-10-19 18:58:36 (218 KB/s) - Read error at byte 2681880576/26349147849 (Connection reset by peer)

so could anyone suggest how to fix this problem or maybe share the data to me?

**Comment by Mingxiao-Li** [comment]
I got the same problems.  Does anyone know how to solve this ?
