### ISSUE TITLE
The link to download Pretrained features_36 is unavailable.  

### ISSUE THREAD

**Issue by Mingxiao-Li** [peteanderson80/bottom-up-attention#96]
Hi, Could make a new link to download the feature_36 data ? I kept getting errors during downloading using current link.

**Comment by pasinit** [comment]
Confirm, I am having the same problem. With wget I get this error:
`2021-01-04 10:09:44 (621 KB/s) - Read error at byte 18300715008/26349147849 (Connection reset by peer). Retrying.`
`2021-01-04 00:58:35--  (try:16)  https://imagecaption.blob.core.windows.net/imagecaption/trainval_36.zip
Connecting to imagecaption.blob.core.windows.net (imagecaption.blob.core.windows.net)|52.239.161.42|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26349147849 (25G) [application/x-zip-compressed]
Saving to: ‘trainval_36.zip’`

**Comment by MinionAttack** [comment]
I have a problem too:

`ConnectionResetError: [Errno 104] Connection reset by peer` 

I'm unable to download the file.
